from PyQt5 import QtCore, QtGui, QtWidgets

# ForecastDialog design
class Ui_ForecastDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(618, 718)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(618, 718))
        Dialog.setMaximumSize(QtCore.QSize(618, 718))
        font = QtGui.QFont()
        font.setPointSize(24)
        Dialog.setFont(font)
        Dialog.setMouseTracking(False)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(600, 700))
        self.scrollArea.setMaximumSize(QtCore.QSize(600, 700))
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -394, 570, 1090))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setVerticalSpacing(12)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.headerStatus = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.headerStatus.setFont(font)
        self.headerStatus.setObjectName("headerStatus")
        self.horizontalLayout.addWidget(self.headerStatus, 0, QtCore.Qt.AlignLeft)
        self.headerStatusIcon = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.headerStatusIcon.setFont(font)
        self.headerStatusIcon.setObjectName("headerStatusIcon")
        self.horizontalLayout.addWidget(self.headerStatusIcon, 0, QtCore.Qt.AlignRight)
        self.headerTemperature = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.headerTemperature.setFont(font)
        self.headerTemperature.setObjectName("headerTemperature")
        self.horizontalLayout.addWidget(self.headerTemperature, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 9, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.wind = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.wind.setFont(font)
        self.wind.setObjectName("wind")
        self.horizontalLayout_4.addWidget(self.wind)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 16, 0, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_2.addWidget(self.line_7, 3, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.day_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.day_7.setFont(font)
        self.day_7.setObjectName("day_7")
        self.horizontalLayout_8.addWidget(self.day_7, 0, QtCore.Qt.AlignLeft)
        self.statusIcon_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.statusIcon_7.setFont(font)
        self.statusIcon_7.setObjectName("statusIcon_7")
        self.horizontalLayout_8.addWidget(self.statusIcon_7, 0, QtCore.Qt.AlignHCenter)
        self.temperature_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.temperature_7.setFont(font)
        self.temperature_7.setObjectName("temperature_7")
        self.horizontalLayout_8.addWidget(self.temperature_7, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 27, 0, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_2.addWidget(self.line_10, 7, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.day_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.day_4.setFont(font)
        self.day_4.setObjectName("day_4")
        self.horizontalLayout_5.addWidget(self.day_4, 0, QtCore.Qt.AlignLeft)
        self.statusIcon_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.statusIcon_4.setFont(font)
        self.statusIcon_4.setObjectName("statusIcon_4")
        self.horizontalLayout_5.addWidget(self.statusIcon_4, 0, QtCore.Qt.AlignHCenter)
        self.temperature_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.temperature_3.setFont(font)
        self.temperature_3.setObjectName("temperature_3")
        self.horizontalLayout_5.addWidget(self.temperature_3, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 23, 0, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_15.addWidget(self.label)
        self.sunrise = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.sunrise.setFont(font)
        self.sunrise.setObjectName("sunrise")
        self.horizontalLayout_15.addWidget(self.sunrise)
        self.gridLayout_2.addLayout(self.horizontalLayout_15, 4, 0, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_2.addWidget(self.line_11, 20, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_12.addWidget(self.label_4)
        self.pressure = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pressure.setFont(font)
        self.pressure.setObjectName("pressure")
        self.horizontalLayout_12.addWidget(self.pressure)
        self.gridLayout_2.addLayout(self.horizontalLayout_12, 10, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        self.feelsLike = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.feelsLike.setFont(font)
        self.feelsLike.setObjectName("feelsLike")
        self.horizontalLayout_10.addWidget(self.feelsLike)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 14, 0, 1, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(525, 110))
        self.scrollArea_2.setMaximumSize(QtCore.QSize(525, 110))
        self.scrollArea_2.setWidgetResizable(False)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 1742, 88))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_49 = QtWidgets.QVBoxLayout()
        self.verticalLayout_49.setObjectName("verticalLayout_49")
        self.hourlyTime_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTime_1.setFont(font)
        self.hourlyTime_1.setObjectName("hourlyTime_1")
        self.verticalLayout_49.addWidget(self.hourlyTime_1, 0, QtCore.Qt.AlignHCenter)
        self.hourlyIcon_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyIcon_1.setFont(font)
        self.hourlyIcon_1.setObjectName("hourlyIcon_1")
        self.verticalLayout_49.addWidget(self.hourlyIcon_1, 0, QtCore.Qt.AlignHCenter)
        self.hourlyTemp_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTemp_1.setFont(font)
        self.hourlyTemp_1.setObjectName("hourlyTemp_1")
        self.verticalLayout_49.addWidget(self.hourlyTemp_1, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_18.addLayout(self.verticalLayout_49)
        self.verticalLayout_50 = QtWidgets.QVBoxLayout()
        self.verticalLayout_50.setObjectName("verticalLayout_50")
        self.hourlyTime_50 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTime_50.setFont(font)
        self.hourlyTime_50.setObjectName("hourlyTime_50")
        self.verticalLayout_50.addWidget(self.hourlyTime_50, 0, QtCore.Qt.AlignHCenter)
        self.hourlyIcon_50 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyIcon_50.setFont(font)
        self.hourlyIcon_50.setObjectName("hourlyIcon_50")
        self.verticalLayout_50.addWidget(self.hourlyIcon_50, 0, QtCore.Qt.AlignHCenter)
        self.hourlyTemp_50 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTemp_50.setFont(font)
        self.hourlyTemp_50.setObjectName("hourlyTemp_50")
        self.verticalLayout_50.addWidget(self.hourlyTemp_50, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_18.addLayout(self.verticalLayout_50)
        self.verticalLayout_51 = QtWidgets.QVBoxLayout()
        self.verticalLayout_51.setObjectName("verticalLayout_51")
        self.hourlyTime_51 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTime_51.setFont(font)
        self.hourlyTime_51.setObjectName("hourlyTime_51")
        self.verticalLayout_51.addWidget(self.hourlyTime_51, 0, QtCore.Qt.AlignHCenter)
        self.hourlyIcon_51 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyIcon_51.setFont(font)
        self.hourlyIcon_51.setObjectName("hourlyIcon_51")
        self.verticalLayout_51.addWidget(self.hourlyIcon_51, 0, QtCore.Qt.AlignHCenter)
        self.hourlyTemp_51 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTemp_51.setFont(font)
        self.hourlyTemp_51.setObjectName("hourlyTemp_51")
        self.verticalLayout_51.addWidget(self.hourlyTemp_51, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_18.addLayout(self.verticalLayout_51)
        self.verticalLayout_52 = QtWidgets.QVBoxLayout()
        self.verticalLayout_52.setObjectName("verticalLayout_52")
        self.hourlyTime_52 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTime_52.setFont(font)
        self.hourlyTime_52.setObjectName("hourlyTime_52")
        self.verticalLayout_52.addWidget(self.hourlyTime_52, 0, QtCore.Qt.AlignHCenter)
        self.hourlyIcon_52 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyIcon_52.setFont(font)
        self.hourlyIcon_52.setObjectName("hourlyIcon_52")
        self.verticalLayout_52.addWidget(self.hourlyIcon_52, 0, QtCore.Qt.AlignHCenter)
        self.hourlyTemp_52 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTemp_52.setFont(font)
        self.hourlyTemp_52.setObjectName("hourlyTemp_52")
        self.verticalLayout_52.addWidget(self.hourlyTemp_52, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_18.addLayout(self.verticalLayout_52)
        self.verticalLayout_53 = QtWidgets.QVBoxLayout()
        self.verticalLayout_53.setObjectName("verticalLayout_53")
        self.hourlyTime_53 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTime_53.setFont(font)
        self.hourlyTime_53.setObjectName("hourlyTime_53")
        self.verticalLayout_53.addWidget(self.hourlyTime_53, 0, QtCore.Qt.AlignHCenter)
        self.hourlyIcon_53 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyIcon_53.setFont(font)
        self.hourlyIcon_53.setObjectName("hourlyIcon_53")
        self.verticalLayout_53.addWidget(self.hourlyIcon_53, 0, QtCore.Qt.AlignHCenter)
        self.hourlyTemp_53 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTemp_53.setFont(font)
        self.hourlyTemp_53.setObjectName("hourlyTemp_53")
        self.verticalLayout_53.addWidget(self.hourlyTemp_53, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_18.addLayout(self.verticalLayout_53)
        self.verticalLayout_54 = QtWidgets.QVBoxLayout()
        self.verticalLayout_54.setObjectName("verticalLayout_54")
        self.hourlyTime_54 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTime_54.setFont(font)
        self.hourlyTime_54.setObjectName("hourlyTime_54")
        self.verticalLayout_54.addWidget(self.hourlyTime_54, 0, QtCore.Qt.AlignHCenter)
        self.hourlyIcon_54 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyIcon_54.setFont(font)
        self.hourlyIcon_54.setObjectName("hourlyIcon_54")
        self.verticalLayout_54.addWidget(self.hourlyIcon_54, 0, QtCore.Qt.AlignHCenter)
        self.hourlyTemp_54 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTemp_54.setFont(font)
        self.hourlyTemp_54.setObjectName("hourlyTemp_54")
        self.verticalLayout_54.addWidget(self.hourlyTemp_54, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_18.addLayout(self.verticalLayout_54)
        self.verticalLayout_55 = QtWidgets.QVBoxLayout()
        self.verticalLayout_55.setObjectName("verticalLayout_55")
        self.hourlyTime_55 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTime_55.setFont(font)
        self.hourlyTime_55.setObjectName("hourlyTime_55")
        self.verticalLayout_55.addWidget(self.hourlyTime_55, 0, QtCore.Qt.AlignHCenter)
        self.hourlyIcon_55 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyIcon_55.setFont(font)
        self.hourlyIcon_55.setObjectName("hourlyIcon_55")
        self.verticalLayout_55.addWidget(self.hourlyIcon_55, 0, QtCore.Qt.AlignHCenter)
        self.hourlyTemp_55 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTemp_55.setFont(font)
        self.hourlyTemp_55.setObjectName("hourlyTemp_55")
        self.verticalLayout_55.addWidget(self.hourlyTemp_55, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_18.addLayout(self.verticalLayout_55)
        self.verticalLayout_56 = QtWidgets.QVBoxLayout()
        self.verticalLayout_56.setObjectName("verticalLayout_56")
        self.hourlyTime_56 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTime_56.setFont(font)
        self.hourlyTime_56.setObjectName("hourlyTime_56")
        self.verticalLayout_56.addWidget(self.hourlyTime_56, 0, QtCore.Qt.AlignHCenter)
        self.hourlyIcon_56 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyIcon_56.setFont(font)
        self.hourlyIcon_56.setObjectName("hourlyIcon_56")
        self.verticalLayout_56.addWidget(self.hourlyIcon_56, 0, QtCore.Qt.AlignHCenter)
        self.hourlyTemp_56 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTemp_56.setFont(font)
        self.hourlyTemp_56.setObjectName("hourlyTemp_56")
        self.verticalLayout_56.addWidget(self.hourlyTemp_56, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_18.addLayout(self.verticalLayout_56)
        self.verticalLayout_57 = QtWidgets.QVBoxLayout()
        self.verticalLayout_57.setObjectName("verticalLayout_57")
        self.hourlyTime_57 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTime_57.setFont(font)
        self.hourlyTime_57.setObjectName("hourlyTime_57")
        self.verticalLayout_57.addWidget(self.hourlyTime_57, 0, QtCore.Qt.AlignHCenter)
        self.hourlyIcon_57 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyIcon_57.setFont(font)
        self.hourlyIcon_57.setObjectName("hourlyIcon_57")
        self.verticalLayout_57.addWidget(self.hourlyIcon_57, 0, QtCore.Qt.AlignHCenter)
        self.hourlyTemp_57 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTemp_57.setFont(font)
        self.hourlyTemp_57.setObjectName("hourlyTemp_57")
        self.verticalLayout_57.addWidget(self.hourlyTemp_57, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_18.addLayout(self.verticalLayout_57)
        self.verticalLayout_58 = QtWidgets.QVBoxLayout()
        self.verticalLayout_58.setObjectName("verticalLayout_58")
        self.hourlyTime_58 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTime_58.setFont(font)
        self.hourlyTime_58.setObjectName("hourlyTime_58")
        self.verticalLayout_58.addWidget(self.hourlyTime_58, 0, QtCore.Qt.AlignHCenter)
        self.hourlyIcon_58 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyIcon_58.setFont(font)
        self.hourlyIcon_58.setObjectName("hourlyIcon_58")
        self.verticalLayout_58.addWidget(self.hourlyIcon_58, 0, QtCore.Qt.AlignHCenter)
        self.hourlyTemp_58 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTemp_58.setFont(font)
        self.hourlyTemp_58.setObjectName("hourlyTemp_58")
        self.verticalLayout_58.addWidget(self.hourlyTemp_58, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_18.addLayout(self.verticalLayout_58)
        self.verticalLayout_59 = QtWidgets.QVBoxLayout()
        self.verticalLayout_59.setObjectName("verticalLayout_59")
        self.hourlyTime_59 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTime_59.setFont(font)
        self.hourlyTime_59.setObjectName("hourlyTime_59")
        self.verticalLayout_59.addWidget(self.hourlyTime_59, 0, QtCore.Qt.AlignHCenter)
        self.hourlyIcon_59 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyIcon_59.setFont(font)
        self.hourlyIcon_59.setObjectName("hourlyIcon_59")
        self.verticalLayout_59.addWidget(self.hourlyIcon_59, 0, QtCore.Qt.AlignHCenter)
        self.hourlyTemp_59 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTemp_59.setFont(font)
        self.hourlyTemp_59.setObjectName("hourlyTemp_59")
        self.verticalLayout_59.addWidget(self.hourlyTemp_59, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_18.addLayout(self.verticalLayout_59)
        self.verticalLayout_60 = QtWidgets.QVBoxLayout()
        self.verticalLayout_60.setObjectName("verticalLayout_60")
        self.hourlyTime_60 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTime_60.setFont(font)
        self.hourlyTime_60.setObjectName("hourlyTime_60")
        self.verticalLayout_60.addWidget(self.hourlyTime_60, 0, QtCore.Qt.AlignHCenter)
        self.hourlyIcon_60 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyIcon_60.setFont(font)
        self.hourlyIcon_60.setObjectName("hourlyIcon_60")
        self.verticalLayout_60.addWidget(self.hourlyIcon_60, 0, QtCore.Qt.AlignHCenter)
        self.hourlyTemp_60 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTemp_60.setFont(font)
        self.hourlyTemp_60.setObjectName("hourlyTemp_60")
        self.verticalLayout_60.addWidget(self.hourlyTemp_60, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_18.addLayout(self.verticalLayout_60)
        self.verticalLayout_61 = QtWidgets.QVBoxLayout()
        self.verticalLayout_61.setObjectName("verticalLayout_61")
        self.hourlyTime_61 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTime_61.setFont(font)
        self.hourlyTime_61.setObjectName("hourlyTime_61")
        self.verticalLayout_61.addWidget(self.hourlyTime_61, 0, QtCore.Qt.AlignHCenter)
        self.hourlyIcon_61 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyIcon_61.setFont(font)
        self.hourlyIcon_61.setObjectName("hourlyIcon_61")
        self.verticalLayout_61.addWidget(self.hourlyIcon_61, 0, QtCore.Qt.AlignHCenter)
        self.hourlyTemp_61 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTemp_61.setFont(font)
        self.hourlyTemp_61.setObjectName("hourlyTemp_61")
        self.verticalLayout_61.addWidget(self.hourlyTemp_61, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_18.addLayout(self.verticalLayout_61)
        self.verticalLayout_62 = QtWidgets.QVBoxLayout()
        self.verticalLayout_62.setObjectName("verticalLayout_62")
        self.hourlyTime_62 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTime_62.setFont(font)
        self.hourlyTime_62.setObjectName("hourlyTime_62")
        self.verticalLayout_62.addWidget(self.hourlyTime_62, 0, QtCore.Qt.AlignHCenter)
        self.hourlyIcon_62 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyIcon_62.setFont(font)
        self.hourlyIcon_62.setObjectName("hourlyIcon_62")
        self.verticalLayout_62.addWidget(self.hourlyIcon_62, 0, QtCore.Qt.AlignHCenter)
        self.hourlyTemp_62 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTemp_62.setFont(font)
        self.hourlyTemp_62.setObjectName("hourlyTemp_62")
        self.verticalLayout_62.addWidget(self.hourlyTemp_62, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_18.addLayout(self.verticalLayout_62)
        self.verticalLayout_63 = QtWidgets.QVBoxLayout()
        self.verticalLayout_63.setObjectName("verticalLayout_63")
        self.hourlyTime_63 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTime_63.setFont(font)
        self.hourlyTime_63.setObjectName("hourlyTime_63")
        self.verticalLayout_63.addWidget(self.hourlyTime_63, 0, QtCore.Qt.AlignHCenter)
        self.hourlyIcon_63 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyIcon_63.setFont(font)
        self.hourlyIcon_63.setObjectName("hourlyIcon_63")
        self.verticalLayout_63.addWidget(self.hourlyIcon_63, 0, QtCore.Qt.AlignHCenter)
        self.hourlyTemp_63 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTemp_63.setFont(font)
        self.hourlyTemp_63.setObjectName("hourlyTemp_63")
        self.verticalLayout_63.addWidget(self.hourlyTemp_63, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_18.addLayout(self.verticalLayout_63)
        self.verticalLayout_64 = QtWidgets.QVBoxLayout()
        self.verticalLayout_64.setObjectName("verticalLayout_64")
        self.hourlyTime_64 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTime_64.setFont(font)
        self.hourlyTime_64.setObjectName("hourlyTime_64")
        self.verticalLayout_64.addWidget(self.hourlyTime_64, 0, QtCore.Qt.AlignHCenter)
        self.hourlyIcon_64 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyIcon_64.setFont(font)
        self.hourlyIcon_64.setObjectName("hourlyIcon_64")
        self.verticalLayout_64.addWidget(self.hourlyIcon_64, 0, QtCore.Qt.AlignHCenter)
        self.hourlyTemp_64 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTemp_64.setFont(font)
        self.hourlyTemp_64.setObjectName("hourlyTemp_64")
        self.verticalLayout_64.addWidget(self.hourlyTemp_64, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_18.addLayout(self.verticalLayout_64)
        self.verticalLayout_65 = QtWidgets.QVBoxLayout()
        self.verticalLayout_65.setObjectName("verticalLayout_65")
        self.hourlyTime_65 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTime_65.setFont(font)
        self.hourlyTime_65.setObjectName("hourlyTime_65")
        self.verticalLayout_65.addWidget(self.hourlyTime_65, 0, QtCore.Qt.AlignHCenter)
        self.hourlyIcon_65 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyIcon_65.setFont(font)
        self.hourlyIcon_65.setObjectName("hourlyIcon_65")
        self.verticalLayout_65.addWidget(self.hourlyIcon_65, 0, QtCore.Qt.AlignHCenter)
        self.hourlyTemp_65 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTemp_65.setFont(font)
        self.hourlyTemp_65.setObjectName("hourlyTemp_65")
        self.verticalLayout_65.addWidget(self.hourlyTemp_65, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_18.addLayout(self.verticalLayout_65)
        self.verticalLayout_66 = QtWidgets.QVBoxLayout()
        self.verticalLayout_66.setObjectName("verticalLayout_66")
        self.hourlyTime_66 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTime_66.setFont(font)
        self.hourlyTime_66.setObjectName("hourlyTime_66")
        self.verticalLayout_66.addWidget(self.hourlyTime_66, 0, QtCore.Qt.AlignHCenter)
        self.hourlyIcon_66 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyIcon_66.setFont(font)
        self.hourlyIcon_66.setObjectName("hourlyIcon_66")
        self.verticalLayout_66.addWidget(self.hourlyIcon_66, 0, QtCore.Qt.AlignHCenter)
        self.hourlyTemp_66 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTemp_66.setFont(font)
        self.hourlyTemp_66.setObjectName("hourlyTemp_66")
        self.verticalLayout_66.addWidget(self.hourlyTemp_66, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_18.addLayout(self.verticalLayout_66)
        self.verticalLayout_67 = QtWidgets.QVBoxLayout()
        self.verticalLayout_67.setObjectName("verticalLayout_67")
        self.hourlyTime_67 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTime_67.setFont(font)
        self.hourlyTime_67.setObjectName("hourlyTime_67")
        self.verticalLayout_67.addWidget(self.hourlyTime_67, 0, QtCore.Qt.AlignHCenter)
        self.hourlyIcon_67 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyIcon_67.setFont(font)
        self.hourlyIcon_67.setObjectName("hourlyIcon_67")
        self.verticalLayout_67.addWidget(self.hourlyIcon_67, 0, QtCore.Qt.AlignHCenter)
        self.hourlyTemp_67 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTemp_67.setFont(font)
        self.hourlyTemp_67.setObjectName("hourlyTemp_67")
        self.verticalLayout_67.addWidget(self.hourlyTemp_67, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_18.addLayout(self.verticalLayout_67)
        self.verticalLayout_68 = QtWidgets.QVBoxLayout()
        self.verticalLayout_68.setObjectName("verticalLayout_68")
        self.hourlyTime_68 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTime_68.setFont(font)
        self.hourlyTime_68.setObjectName("hourlyTime_68")
        self.verticalLayout_68.addWidget(self.hourlyTime_68, 0, QtCore.Qt.AlignHCenter)
        self.hourlyIcon_68 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyIcon_68.setFont(font)
        self.hourlyIcon_68.setObjectName("hourlyIcon_68")
        self.verticalLayout_68.addWidget(self.hourlyIcon_68, 0, QtCore.Qt.AlignHCenter)
        self.hourlyTemp_68 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTemp_68.setFont(font)
        self.hourlyTemp_68.setObjectName("hourlyTemp_68")
        self.verticalLayout_68.addWidget(self.hourlyTemp_68, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_18.addLayout(self.verticalLayout_68)
        self.verticalLayout_69 = QtWidgets.QVBoxLayout()
        self.verticalLayout_69.setObjectName("verticalLayout_69")
        self.hourlyTime_69 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTime_69.setFont(font)
        self.hourlyTime_69.setObjectName("hourlyTime_69")
        self.verticalLayout_69.addWidget(self.hourlyTime_69, 0, QtCore.Qt.AlignHCenter)
        self.hourlyIcon_69 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyIcon_69.setFont(font)
        self.hourlyIcon_69.setObjectName("hourlyIcon_69")
        self.verticalLayout_69.addWidget(self.hourlyIcon_69, 0, QtCore.Qt.AlignHCenter)
        self.hourlyTemp_69 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTemp_69.setFont(font)
        self.hourlyTemp_69.setObjectName("hourlyTemp_69")
        self.verticalLayout_69.addWidget(self.hourlyTemp_69, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_18.addLayout(self.verticalLayout_69)
        self.verticalLayout_70 = QtWidgets.QVBoxLayout()
        self.verticalLayout_70.setObjectName("verticalLayout_70")
        self.hourlyTime_70 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTime_70.setFont(font)
        self.hourlyTime_70.setObjectName("hourlyTime_70")
        self.verticalLayout_70.addWidget(self.hourlyTime_70, 0, QtCore.Qt.AlignHCenter)
        self.hourlyIcon_70 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyIcon_70.setFont(font)
        self.hourlyIcon_70.setObjectName("hourlyIcon_70")
        self.verticalLayout_70.addWidget(self.hourlyIcon_70, 0, QtCore.Qt.AlignHCenter)
        self.hourlyTemp_70 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTemp_70.setFont(font)
        self.hourlyTemp_70.setObjectName("hourlyTemp_70")
        self.verticalLayout_70.addWidget(self.hourlyTemp_70, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_18.addLayout(self.verticalLayout_70)
        self.verticalLayout_71 = QtWidgets.QVBoxLayout()
        self.verticalLayout_71.setObjectName("verticalLayout_71")
        self.hourlyTime_71 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTime_71.setFont(font)
        self.hourlyTime_71.setObjectName("hourlyTime_71")
        self.verticalLayout_71.addWidget(self.hourlyTime_71, 0, QtCore.Qt.AlignHCenter)
        self.hourlyIcon_71 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyIcon_71.setFont(font)
        self.hourlyIcon_71.setObjectName("hourlyIcon_71")
        self.verticalLayout_71.addWidget(self.hourlyIcon_71, 0, QtCore.Qt.AlignHCenter)
        self.hourlyTemp_71 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTemp_71.setFont(font)
        self.hourlyTemp_71.setObjectName("hourlyTemp_71")
        self.verticalLayout_71.addWidget(self.hourlyTemp_71, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_18.addLayout(self.verticalLayout_71)
        self.verticalLayout_72 = QtWidgets.QVBoxLayout()
        self.verticalLayout_72.setObjectName("verticalLayout_72")
        self.hourlyTime_72 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTime_72.setFont(font)
        self.hourlyTime_72.setObjectName("hourlyTime_72")
        self.verticalLayout_72.addWidget(self.hourlyTime_72, 0, QtCore.Qt.AlignHCenter)
        self.hourlyIcon_72 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyIcon_72.setFont(font)
        self.hourlyIcon_72.setObjectName("hourlyIcon_72")
        self.verticalLayout_72.addWidget(self.hourlyIcon_72, 0, QtCore.Qt.AlignHCenter)
        self.hourlyTemp_72 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hourlyTemp_72.setFont(font)
        self.hourlyTemp_72.setObjectName("hourlyTemp_72")
        self.verticalLayout_72.addWidget(self.hourlyTemp_72, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_18.addLayout(self.verticalLayout_72)
        self.gridLayout_5.addLayout(self.horizontalLayout_18, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout_2.addWidget(self.scrollArea_2, 18, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 13, 0, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_2.addWidget(self.line_9, 5, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.day_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.day_6.setFont(font)
        self.day_6.setObjectName("day_6")
        self.horizontalLayout_7.addWidget(self.day_6, 0, QtCore.Qt.AlignLeft)
        self.statusIcon_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.statusIcon_6.setFont(font)
        self.statusIcon_6.setObjectName("statusIcon_6")
        self.horizontalLayout_7.addWidget(self.statusIcon_6, 0, QtCore.Qt.AlignHCenter)
        self.temperature_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.temperature_6.setFont(font)
        self.temperature_6.setObjectName("temperature_6")
        self.horizontalLayout_7.addWidget(self.temperature_6, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 26, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_11.addWidget(self.label_5)
        self.visibility = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.visibility.setFont(font)
        self.visibility.setObjectName("visibility")
        self.horizontalLayout_11.addWidget(self.visibility)
        self.gridLayout_2.addLayout(self.horizontalLayout_11, 12, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.day_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.day_5.setFont(font)
        self.day_5.setObjectName("day_5")
        self.horizontalLayout_6.addWidget(self.day_5, 0, QtCore.Qt.AlignLeft)
        self.statusIcon_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.statusIcon_5.setFont(font)
        self.statusIcon_5.setObjectName("statusIcon_5")
        self.horizontalLayout_6.addWidget(self.statusIcon_5, 0, QtCore.Qt.AlignHCenter)
        self.temperature_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.temperature_5.setFont(font)
        self.temperature_5.setObjectName("temperature_5")
        self.horizontalLayout_6.addWidget(self.temperature_5, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 25, 0, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_2.addWidget(self.line_8, 11, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_2.addWidget(self.line_5, 15, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_14.addWidget(self.label_2)
        self.sunset = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.sunset.setFont(font)
        self.sunset.setObjectName("sunset")
        self.horizontalLayout_14.addWidget(self.sunset)
        self.gridLayout_2.addLayout(self.horizontalLayout_14, 6, 0, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout_2.addWidget(self.line_12, 17, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.day_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.day_8.setFont(font)
        self.day_8.setObjectName("day_8")
        self.horizontalLayout_9.addWidget(self.day_8, 0, QtCore.Qt.AlignLeft)
        self.statusIcon_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.statusIcon_8.setFont(font)
        self.statusIcon_8.setObjectName("statusIcon_8")
        self.horizontalLayout_9.addWidget(self.statusIcon_8, 0, QtCore.Qt.AlignHCenter)
        self.temperature_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.temperature_8.setFont(font)
        self.temperature_8.setObjectName("temperature_8")
        self.horizontalLayout_9.addWidget(self.temperature_8, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 28, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_13.addWidget(self.label_3)
        self.humidity = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.humidity.setFont(font)
        self.humidity.setObjectName("humidity")
        self.horizontalLayout_13.addWidget(self.humidity)
        self.gridLayout_2.addLayout(self.horizontalLayout_13, 8, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.day_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.day_2.setFont(font)
        self.day_2.setObjectName("day_2")
        self.horizontalLayout_3.addWidget(self.day_2, 0, QtCore.Qt.AlignLeft)
        self.statusIcon_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.statusIcon_2.setFont(font)
        self.statusIcon_2.setObjectName("statusIcon_2")
        self.horizontalLayout_3.addWidget(self.statusIcon_2, 0, QtCore.Qt.AlignHCenter)
        self.temperature_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.temperature_2.setFont(font)
        self.temperature_2.setObjectName("temperature_2")
        self.horizontalLayout_3.addWidget(self.temperature_2, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 21, 0, 1, 1)
        self.placeName = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.placeName.setFont(font)
        self.placeName.setAlignment(QtCore.Qt.AlignCenter)
        self.placeName.setObjectName("placeName")
        self.gridLayout_2.addWidget(self.placeName, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.day_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.day_3.setFont(font)
        self.day_3.setObjectName("day_3")
        self.horizontalLayout_2.addWidget(self.day_3, 0, QtCore.Qt.AlignLeft)
        self.statusIcon_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.statusIcon_3.setFont(font)
        self.statusIcon_3.setObjectName("statusIcon_3")
        self.horizontalLayout_2.addWidget(self.statusIcon_3, 0, QtCore.Qt.AlignHCenter)
        self.temperature_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.temperature_4.setFont(font)
        self.temperature_4.setObjectName("temperature_4")
        self.horizontalLayout_2.addWidget(self.temperature_4, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 22, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Погода"))
        self.headerStatus.setText(_translate("Dialog", "TextLabel"))
        self.headerStatusIcon.setText(_translate("Dialog", "TextLabel"))
        self.headerTemperature.setText(_translate("Dialog", "TextLabel"))
        self.label_7.setText(_translate("Dialog", "Ветер:"))
        self.wind.setText(_translate("Dialog", "TextLabel"))
        self.day_7.setText(_translate("Dialog", "TextLabel"))
        self.statusIcon_7.setText(_translate("Dialog", "TextLabel"))
        self.temperature_7.setText(_translate("Dialog", "TextLabel"))
        self.day_4.setText(_translate("Dialog", "TextLabel"))
        self.statusIcon_4.setText(_translate("Dialog", "TextLabel"))
        self.temperature_3.setText(_translate("Dialog", "TextLabel"))
        self.label.setText(_translate("Dialog", "Рассвет:"))
        self.sunrise.setText(_translate("Dialog", "TextLabel"))
        self.label_4.setText(_translate("Dialog", "Давление:"))
        self.pressure.setText(_translate("Dialog", "TextLabel"))
        self.label_6.setText(_translate("Dialog", "Ощущается как:"))
        self.feelsLike.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTime_1.setText(_translate("Dialog", "TextLabel"))
        self.hourlyIcon_1.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTemp_1.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTime_50.setText(_translate("Dialog", "TextLabel"))
        self.hourlyIcon_50.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTemp_50.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTime_51.setText(_translate("Dialog", "TextLabel"))
        self.hourlyIcon_51.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTemp_51.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTime_52.setText(_translate("Dialog", "TextLabel"))
        self.hourlyIcon_52.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTemp_52.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTime_53.setText(_translate("Dialog", "TextLabel"))
        self.hourlyIcon_53.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTemp_53.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTime_54.setText(_translate("Dialog", "TextLabel"))
        self.hourlyIcon_54.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTemp_54.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTime_55.setText(_translate("Dialog", "TextLabel"))
        self.hourlyIcon_55.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTemp_55.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTime_56.setText(_translate("Dialog", "TextLabel"))
        self.hourlyIcon_56.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTemp_56.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTime_57.setText(_translate("Dialog", "TextLabel"))
        self.hourlyIcon_57.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTemp_57.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTime_58.setText(_translate("Dialog", "TextLabel"))
        self.hourlyIcon_58.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTemp_58.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTime_59.setText(_translate("Dialog", "TextLabel"))
        self.hourlyIcon_59.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTemp_59.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTime_60.setText(_translate("Dialog", "TextLabel"))
        self.hourlyIcon_60.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTemp_60.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTime_61.setText(_translate("Dialog", "TextLabel"))
        self.hourlyIcon_61.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTemp_61.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTime_62.setText(_translate("Dialog", "TextLabel"))
        self.hourlyIcon_62.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTemp_62.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTime_63.setText(_translate("Dialog", "TextLabel"))
        self.hourlyIcon_63.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTemp_63.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTime_64.setText(_translate("Dialog", "TextLabel"))
        self.hourlyIcon_64.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTemp_64.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTime_65.setText(_translate("Dialog", "TextLabel"))
        self.hourlyIcon_65.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTemp_65.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTime_66.setText(_translate("Dialog", "TextLabel"))
        self.hourlyIcon_66.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTemp_66.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTime_67.setText(_translate("Dialog", "TextLabel"))
        self.hourlyIcon_67.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTemp_67.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTime_68.setText(_translate("Dialog", "TextLabel"))
        self.hourlyIcon_68.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTemp_68.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTime_69.setText(_translate("Dialog", "TextLabel"))
        self.hourlyIcon_69.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTemp_69.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTime_70.setText(_translate("Dialog", "TextLabel"))
        self.hourlyIcon_70.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTemp_70.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTime_71.setText(_translate("Dialog", "TextLabel"))
        self.hourlyIcon_71.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTemp_71.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTime_72.setText(_translate("Dialog", "TextLabel"))
        self.hourlyIcon_72.setText(_translate("Dialog", "TextLabel"))
        self.hourlyTemp_72.setText(_translate("Dialog", "TextLabel"))
        self.day_6.setText(_translate("Dialog", "TextLabel"))
        self.statusIcon_6.setText(_translate("Dialog", "TextLabel"))
        self.temperature_6.setText(_translate("Dialog", "TextLabel"))
        self.label_5.setText(_translate("Dialog", "Видимость:"))
        self.visibility.setText(_translate("Dialog", "TextLabel"))
        self.day_5.setText(_translate("Dialog", "TextLabel"))
        self.statusIcon_5.setText(_translate("Dialog", "TextLabel"))
        self.temperature_5.setText(_translate("Dialog", "TextLabel"))
        self.label_2.setText(_translate("Dialog", "Закат:"))
        self.sunset.setText(_translate("Dialog", "TextLabel"))
        self.day_8.setText(_translate("Dialog", "TextLabel"))
        self.statusIcon_8.setText(_translate("Dialog", "TextLabel"))
        self.temperature_8.setText(_translate("Dialog", "TextLabel"))
        self.label_3.setText(_translate("Dialog", "Влажность:"))
        self.humidity.setText(_translate("Dialog", "TextLabel"))
        self.day_2.setText(_translate("Dialog", "TextLabel"))
        self.statusIcon_2.setText(_translate("Dialog", "TextLabel"))
        self.temperature_2.setText(_translate("Dialog", "TextLabel"))
        self.placeName.setText(_translate("Dialog", "TextLabel"))
        self.day_3.setText(_translate("Dialog", "TextLabel"))
        self.statusIcon_3.setText(_translate("Dialog", "TextLabel"))
        self.temperature_4.setText(_translate("Dialog", "TextLabel"))