# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'list.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CitiesList(object):
    def setupUi(self, CitiesList):
        CitiesList.setObjectName("CitiesList")
        CitiesList.resize(674, 521)
        self.gridLayout = QtWidgets.QGridLayout(CitiesList)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(CitiesList)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.listWidget = QtWidgets.QListWidget(CitiesList)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.addButton = QtWidgets.QPushButton(CitiesList)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addButton.setFont(font)
        self.addButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addButton.setObjectName("addButton")
        self.verticalLayout_2.addWidget(self.addButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.openButton = QtWidgets.QPushButton(CitiesList)
        self.openButton.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.openButton.setFont(font)
        self.openButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.openButton.setObjectName("openButton")
        self.verticalLayout_2.addWidget(self.openButton)
        self.deleteButton = QtWidgets.QPushButton(CitiesList)
        self.deleteButton.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deleteButton.setFont(font)
        self.deleteButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deleteButton.setObjectName("deleteButton")
        self.verticalLayout_2.addWidget(self.deleteButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem2)
        self.deleteAllButton = QtWidgets.QPushButton(CitiesList)
        self.deleteAllButton.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deleteAllButton.setFont(font)
        self.deleteAllButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deleteAllButton.setObjectName("deleteAllButton")
        self.verticalLayout_2.addWidget(self.deleteAllButton)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)

        self.retranslateUi(CitiesList)
        QtCore.QMetaObject.connectSlotsByName(CitiesList)

    def retranslateUi(self, CitiesList):
        _translate = QtCore.QCoreApplication.translate
        CitiesList.setWindowTitle(_translate("CitiesList", "Form"))
        self.label.setText(_translate("CitiesList", "Список ваших точек"))
        self.listWidget.setSortingEnabled(True)
        self.addButton.setText(_translate("CitiesList", "Добавить"))
        self.openButton.setText(_translate("CitiesList", "Открыть"))
        self.deleteButton.setText(_translate("CitiesList", "Удалить"))
        self.deleteAllButton.setText(_translate("CitiesList", "Удалить все"))
