# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartMenu(object):
    def setupUi(self, StartMenu):
        StartMenu.setObjectName("StartMenu")
        StartMenu.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(17)
        StartMenu.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(StartMenu)
        self.gridLayout.setObjectName("gridLayout")
        self.geolocationWeatherButton = QtWidgets.QPushButton(StartMenu)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.geolocationWeatherButton.setFont(font)
        self.geolocationWeatherButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.geolocationWeatherButton.setObjectName("geolocationWeatherButton")
        self.gridLayout.addWidget(self.geolocationWeatherButton, 5, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.startButton = QtWidgets.QPushButton(StartMenu)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.startButton.setFont(font)
        self.startButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startButton.setStyleSheet("")
        self.startButton.setObjectName("startButton")
        self.gridLayout.addWidget(self.startButton, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(StartMenu)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 6, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem3, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 2, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem5, 4, 2, 1, 1)

        self.retranslateUi(StartMenu)
        QtCore.QMetaObject.connectSlotsByName(StartMenu)

    def retranslateUi(self, StartMenu):
        _translate = QtCore.QCoreApplication.translate
        StartMenu.setWindowTitle(_translate("StartMenu", "Form"))
        self.geolocationWeatherButton.setText(_translate("StartMenu", "Текущее местоположение"))
        self.startButton.setText(_translate("StartMenu", "Выбрать место"))
        self.label.setText(_translate("StartMenu", "Погода"))
